// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARp9sIRSzkyJjekxAQdoYroisjZBFo6Ek',
    appId: '1:779155206334:web:87b0ecf0c0e6a2653caeef',
    messagingSenderId: '779155206334',
    projectId: 'zolatte-assignment-ef40e',
    authDomain: 'zolatte-assignment-ef40e.firebaseapp.com',
    storageBucket: 'zolatte-assignment-ef40e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn07PD9zC_q7WB23LWKbhh-v-gbCOJNbU',
    appId: '1:779155206334:android:cf32d1eeb73abf7f3caeef',
    messagingSenderId: '779155206334',
    projectId: 'zolatte-assignment-ef40e',
    storageBucket: 'zolatte-assignment-ef40e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUFP8krkMchZx1Tp3GgmT5lD26tsTwuc',
    appId: '1:779155206334:ios:67b6c1bd92aef6383caeef',
    messagingSenderId: '779155206334',
    projectId: 'zolatte-assignment-ef40e',
    storageBucket: 'zolatte-assignment-ef40e.appspot.com',
    iosClientId: '779155206334-9vnskit7lkdd7du73etscp239o28tlp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.zolatteAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUFP8krkMchZx1Tp3GgmT5lD26tsTwuc',
    appId: '1:779155206334:ios:67b6c1bd92aef6383caeef',
    messagingSenderId: '779155206334',
    projectId: 'zolatte-assignment-ef40e',
    storageBucket: 'zolatte-assignment-ef40e.appspot.com',
    iosClientId: '779155206334-9vnskit7lkdd7du73etscp239o28tlp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.zolatteAssignment',
  );
}
